gems:
  - jekyll-sitemap

# Build settings
kramdown:
    input: GFM
    coderay_line_numbers: nil
    hard_wrap: false

#Site content configuration
javadoc_url: /javadoc_5.x/
github_core_main_url: https://github.com/javers/javers/blob/master/javers-core/src/main/java/
github_spring_main_url: https://github.com/javers/javers/blob/master/javers-spring/src/main/java/
github_core_test_url: https://github.com/javers/javers/blob/master/javers-core/src/test/groovy/
javers_current_version: "5.9.2"

url: "https://javers.org"

description: Object auditing and diff framework for Java

permalink: /blog/:year/:month/:title.html

