gems:
  - jekyll-sitemap

# Build settings
kramdown:
    input: GFM
    coderay_line_numbers: nil
    hard_wrap: false

#Site content configuration
javadoc_url: /javadoc_5.x/
javers_current_version: "5.0.1"

javers_java7_version: "2.9.2"

url: "https://javers.org"

description: Object auditing and diff framework for Java

permalink: /blog/:year/:month/:title.html

